<HTML>
<HEAD>
<title>Administracion Sistema Carpetas :: Asignar Materias</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</HEAD>
<!--SCRIPTS PRIMERO HAY QUE VINCULAR LA LIBERIA JQUERY PARA QUE RECONOZCA EL $-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<!--SCRIPTS-->
	<script src="scripts/carpetas.js"> </script>
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
	<link rel="icon" href="favicon.ico">
	<link rel="stylesheet" href="styles/normalize.css">
	<link rel="stylesheet" href="styles/disenioGastardosAPP.css">


    <link rel="stylesheet" href="styles/demo.css">
    <link rel="stylesheet" href="styles/iconstyle.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

     <!-- Estilos CSS -->
     <link rel="stylesheet" href="styles/estiloGaleriaCarpetas.css">

<script>
function agrandar(imagenSeleccionada)
{  
//    imgShow("#outerdiv", "#innerdiv", "#bigimg",imagenSeleccionada);  
 
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	$(document).ready(function(){

			var f=new Date();
			var FechaHoy = f.getFullYear()-1 ;
			fechainicial = FechaHoy -10;
			fechaFinal   = FechaHoy +10;
			for (var i = fechainicial; i < fechaFinal; i++) 
			{
				if(i == FechaHoy) $("#ianio").prepend('<option selected>' + (i + 1) + '</option>');
				else  $("#ianio").prepend('<option>' + (i + 1) + '</option>');
			}
/*
			//NO NECESITO LEER EL AÑO DE LA SESION...
			var anioSession = 0;
				anioSession = leersesion("IANIO");
			//$(".errores").html("anio en sesion: "+anioSession);
			if(anioSession  != 0)
					$("#ianio").val(anioSession);
*/
	//LEER EL AÑO DESDE LOS PARAMETROS...
			var anioparametros=parametroURL('ianio');
			if(anioparametros != null || anioparametros != undefined)
				$("#ianio").val(anioparametros);
				
			$("#ianio").hide();	//.prop('display', 'none');
			$("#anioTexto").append($("#ianio").val());
			//$("#cursosver").prop('disabled', true);
			$("#cursosver").hide();

		var llamador=parametroURL('llama');

		var materiaParm="";
			materiaParm = parametroURL('materia');
		var persona = 0;
		var docente = 0;
		if(llamador == 'INDEX'){
				persona = parametroURL('idpersonaINI');
				docente = parametroURL('docenteINI');
			
		}
		else
		{
		  persona = parametroURL('idpersona');
		  docente = parametroURL('docente');

		}
		$("#fitroGaleria2").val('ESTAQUINCENA');
		
//+++++++++++++++++++++++++++++++LLAMADA AL GET+++++++++++++++++++++++++++++++++++++++++++++++++++++				
		//SIEMPRE LLEGA UN DOCENTE Y UN ALUMNO, 
			//AL LLAMAR DESDE INDEX, SOLO OCURRE EN LA CARGA LA PRIMERA VEZ
		pedirPersonaTipoEspecialista('#alumnos','ALUMNO',docente);	
			pedirDocente('#profesionalSeleccionado',docente,'ESPECIALISTA');	
				$("#alumnos").val(persona);
			llamador='VER';
			var anioAnalisis = $("#ianio").val();
				pedirMaterias3('#grillamaterias',persona,anioAnalisis,llamador,materiaParm,docente,'#cursoSeleccionado');	 
		pedirGaleria("div[name='Xgal']",persona,anioAnalisis,$("#fitroGaleria2").val(),materiaParm);
			
		$("#volver").on("click",function()
		{
			
			window.location="index.php";
		});
		// boton apagar/prender MENU	
		$(".dropdown").on("click",function()
		{
			$(".dropdown-child").toggle();
		
		});		
		//CUANDO CAMBIO EL ALUMNO QUE VISUALIZO, SE CARGAN SUS MATERIAS..
		$("#alumnos").on("change",function()
		{
			llamador='VER';//$('#profesionales').val()
			var url = "verMateriasAlumno.php?idpersona="+$("#alumnos").val()+"&llama="+llamador+"&docente="+docente;
			window.location.replace(url);
		});				
		$("#profesionales").prop('disabled', true);
		$("#profesionales").hide();

		$("#fitroGaleria2").on("change",function()
		{
			pedirGaleria("div[name='Xgal']",persona,anioAnalisis,$("#fitroGaleria2").val(),materiaParm);
		});				
		
});
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
</script>
<style>
	SELECT{
		display:block;
	}	
</style>
<BODY>
<?php
	include('header.html');
?>	

<div class="errores"></div>

<div class="dropdown">
  <button class="mainmenubtn"><span class="icon-layers fuenteGrande"></span></button>
</div> 
<div class="dropdown-child">
<div class="VerMat">
		<div class="itemvm1">Materias año: <span id="anioTexto" class="valoresFijos"></span> </div>
		<div class="itemvm11">
				<select id="ianio" name="ianio" class="ianio">
					<option value="9999">Seleccionar año...</option>
				</select>
	   </div>
	   	<div class="itemvm2">				
				<select id="profesionales" class="personaSel">
	  		  			<option value="9999">Seleccione persona</option>
	  		  	</select>
	  		  	<span id="profesionalSeleccionado" class="valoresFijos"></span>
		</div>
		<div class="itemvm3">	
	  		  		<select id="alumnos" class="personaSel">
	  		  			<option value="9999">Seleccione persona</option>
	  		  		</select>
					<span id="alumnoSeleccionado" class="valoresFijos"></span>	  		  		
		</div>
		<div class="itemvm4"></div>
		<div class="itemvm44">
		<select id="cursosver" class="cursoSel">
	  		<option value="9999">Seleccione curso</option>
	  	</select>
	  	<span id="cursoSeleccionado" class="valoresFijos15PX"></span>	  		  		
		</div>
		<div class="itemvm5">
	  		  	<button class="accionBoton" id="volver" /><span class="icon-arrow-left fuenteGrande"></span>
		</div>
	</div>
	<div id="grillamaterias" class="grillamaterias3">GRILLA DE SELECCION MULTIPLE
	</div>
	</div> <!-- DROPDOWNCHILD-->
<!-- </div>	  MAIN MENU-->
	<!-- GALERIA EN SI MISMA -->
     <main class="container">
          <div class="row">
               <div class="col s12 center-align">
                    <h1 class="titulo">Lightbox</h1>
               </div>
          </div>
          <div class="row">
           <div class="grillaFiltros">
           	<div class="grillaFiltrositem1">FILTROS</div>
           	<div class="grillaFiltrositem2">
           		<select id="fitroGaleria2">
           			<option value="ESTASEMANA">esta semana</option>
           			<option value="ESTAQUINCENA">última quincena</option>
           			<option value="ESTAMES">ultimo mes</option>
           			<option value="ESTATRESM">ultimos tres meses</option>
           			<option value="ESTASEISM">ultimo semestre</option>
           			<option value="ESTAANIO">ultimo año</option>
           		 </select>
           	</div>
           	<div></div>
           	<div></div>
           	<div></div>
           </div>
                    
          </div>
          <div class="row galeria" name="Xgal">
          </div>
     </main>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
     <script src="scripts/mainGaleriaCarpetas.js"></script>
	
</BODY>
</HTML>
